:scheduler:
  :schedule:
    expire_subscriptions:
      cron: "0 0 * * * *"
      class: Espago::ExpireSubscriptionJob
      queue: default
    finalize_payments_job:
      cron: "0 0 * * * *"
      class: Espago::FinalizePaymentJob
      queue: default